grails-app/controllers/customer_support/FormController.groovy
package customer_support

class FormController {

    def index() { }


    def sendEmail() {

        println(params)



        sendMail {
                    to "vito.radovnikovic@hotelstouch.com"
                    from "htouchdummy@gmail.com"
                    subject "Prijava kvara - " + params.product
                    body "Product: " + params.product + "\n\nUser: " + params.userMail + "\n\nBody: " + params.mailContent
                }
        render(view: "sendEmail")

        return

//        Long userID = Long.valueOf(params.product)
//        if(body != null)
//        {
//
//
//            try
//            {
//
//                sendMail {
//                    to email
//                    from "vito.radovnikovic@hotelstouch.com"
//                    subject mailsubject + "\n\n"
//                    body body +" \n\n Contact : " + contact
//                }
//            }
//            catch(Exception e)
//            {
//                e.printStackTrace()
//                println "ERROR!!: Unable to send the notification to email "
//            }
//        }




    }
}

grails-app/views/common/_ajaxError.gsp
<div id="ErrorMessage">
    <g:if test="${flash.error}">
        <script>
            addResponseMessage({
                status: 1,
                message: "${raw(flash.error)}",
                timeout: 10000,
                dismiss: true,
                disableBody: false,
                small: true
            });
        </script>
        ${flash.error = null}
    </g:if>
    <g:if test="${flash.message}">
        <script>
            addResponseMessage({
                status: 0,
                message: "${raw(flash.message)}",
                timeout: 10000,
                dismiss: true,
                disableBody: false,
                small: true
            });
        </script>
        ${flash.message = null}
    </g:if>
    <g:if test="${flash.info}">
        <script>
            addResponseMessage({
                status: 3,
                message: "${raw(flash.info)}",
                timeout: 10000,
                dismiss: true,
                disableBody: false,
                small: true
            });
        </script>
        ${flash.info = null}
    </g:if>
    <g:if test="${flash.warning}">
        <script>
            addResponseMessage({
                status: 2,
                message: "${raw(flash.warning)}",
                timeout: 10000,
                dismiss: true,
                disableBody: false,
                small: true
            });
        </script>
        ${flash.warning = null}
    </g:if>
    <g:if test="${wellInfo}">
        <div class="well text-center">
            <h4>${raw(wellInfo)}</h4>
        </div>
    </g:if>
</div>

grails-app/views/form/index.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
</head>

<body>
<div class="container-fluid">

    <g:render template="/common/ajaxError"></g:render>

     <g:form controller="form" action="sendEmail">
         <form id="fr1" class="form-inline">
         <div class="form-group">
             <label class='control-label' for="productID">Product:</label><br>
             <g:textField name="product" type="text" class="form-control" id="productID"  required="required"/><br>
             <label class='control-label'  for="userID">User:</label><br>
             <g:textField name="userMail" type="text" class="form-control" id="userID"  required="required"/>
             <br>
             <br>

             <br>
             <label class='control-label' for="comment">Description:</label>
                <g:textArea  name="mailContent" class="form-control"  rows="5" id="comment"  value="Explain your issue in detail..." required="required"/>
             <br>
             <br>
             <input id="uploadFile" placeholder="Choose File" disabled="disabled" />
         <div class="fileUpload btn btn-purple">
             <span>Upload</span>
             <input id="uploadBtn" type="file" class="upload" />
         </div>
         <br>
         <br>
         <g:submitButton class="btn btn-purple" name="sendData" value="Submit" id="submit"></g:submitButton>
         <br>
         <br>


 </div>
 </form>


</g:form>
%{--<form id="fr1" class="form-inline">--}%
        %{--<div class="form-group required">--}%
            %{--<label class='control-label' for="productID">Product:</label><br>--}%
            %{--<input type="text" class="form-control" id="productID" disabled ><br>--}%
            %{--<label class='control-label'  for="userID">User:</label><br>--}%
            %{--<input type="text" class="form-control" id="userID" disabled >--}%
            %{--<br>--}%
            %{--<br>--}%
            %{--<label class='control-label' for="titleID">Title:</label><br>--}%
            %{--<input type="text" class="form-control" name="title" id="titleID"  >--}%

            %{--<label class='control-label' for="comment">Description:</label>--}%
            %{--<textarea class="form-control"  rows="5" id="comment"  value="Explain your issue in detail..."></textarea>--}%
        %{--</div>--}%



    %{--</form>--}%
    %{--<br>--}%
    %{--<div class="form-group required">--}%

    %{--</div>--}%
    %{--<br>--}%
    %{--<button type="submit" id="submitID" class="btn btn-primary">Submit</button>--}%
    %{--<br><br>--}%

    %{--<form action="/upload-target" class="dropzone"></form>--}%
    %{--<br><br>--}%
    %{--<div class="alert alert-danger fade in">--}%
        %{--<a href="#"  id="alert" class="close" data-dismiss="alert" aria-label="close">&times;</a>--}%
        %{--<strong>Warning!</strong> All fields are required.--}%


        %{--<br>--}%
        %{--<br>--}%
        %{--<font size="2" color="red"><i>* - This is a required field.</i></font>--}%
    %{--</div>--}%
</div>

<script>
    document.getElementById("uploadBtn").onchange = function () {
        document.getElementById("uploadFile").value = this.value;
    };



</script>
</body>
<script src ="https://code.jquery.com/jquery-2.2.4.min.js"></script>
<script src ="cs_script.js"></script>


<style>
.form-group.required .control-label:after {
    content:"*";
    color:red;
}

</style>
</html>

grails-app/views/form/sendEmail.gsp
<%--
  Created by IntelliJ IDEA.
  User: vito
  Date: 03.11.16.
  Time: 10:51
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
</head>

<body>

<div class="alert alert-success fade in">

    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <strong>Success!</strong> Your message has been sent successfully. Someone will contact You shortly. If You wish to send another, click below.<br> <br>
    <g:link class="btn btn-purple" controller="form" action="index">New ticket</g:link>
    %{--<button class="btn btn-primary">New ticket</button>--}%
</div>

</body>
</html>

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
<head>
	<link href='https://fonts.googleapis.com/css?family=Open+Sans:600,400&subset=latin,latin-ext' rel='stylesheet'
		  type='text/css'>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title><g:layoutTitle default="Customer Support"/></title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" href="${assetPath(src: 'favicon.png')}" type="image/x-icon">
	<asset:stylesheet src="application.css"/>
	<asset:javascript src="application.js"/>
	<g:layoutHead/>
</head>
<body>
<div id="wrapper">
	<g:layoutBody/>
	<br/>
</div>
</body>
</html>